name: test

on: push

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Test template
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Create test repo
        shell: bash -l {0}
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          TARGET_DIRECTORY=$(mktemp -d)
          cp -R . $TARGET_DIRECTORY
          cd $TARGET_DIRECTORY
          rm -rf .git
          git init
          git checkout --orphan main
          git add . &> /dev/null
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "test commit" &> /dev/null
          git push --force https://x-access-token:${ACCESS_TOKEN}@github.com/rodluger/showyourwork-template-minimal-test main
